// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package spanner_features

import (
	"database/sql"
)

type Post struct {
	ID          string
	UserID      string
	Title       sql.NullString
	Status      sql.NullString
	PublishedAt sql.NullTime
}

type User struct {
	ID        string
	Name      sql.NullString
	Score     sql.NullInt64
	Status    sql.NullString
	DeletedAt sql.NullTime
}
