// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: simple_test.sql

package spanner_features

import (
	"context"
)

const simpleCase = `-- name: SimpleCase :one
SELECT 
  CASE 
    WHEN score >= 90 THEN 'A'
    ELSE 'B'
  END as grade
FROM users WHERE id = @user_id;
`

func (q *Queries) SimpleCase(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, simpleCase, id)
	var grade string
	err := row.Scan(&grade)
	return grade, err
}
