// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package spanner_test

import (
	"database/sql"
)

type User struct {
	ID    string
	Name  sql.NullString
	Email sql.NullString
}
